
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "75"
	#Energy per operation tick (Joules).
	osmiumCompressor = "125"
	#Energy per operation tick (Joules).
	combiner = "75"
	#Energy per operation tick (Joules).
	crusher = "75"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "75"
	#Energy per operation tick (Joules).
	purificationChamber = "300"
	#Energy per operation tick (Joules).
	energizedSmelter = "75"
	#Energy per operation tick (Joules).
	digitalMiner = "1500"
	#Energy per operation tick (Joules).
	electricPump = "150"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "75"
	#Energy per operation tick (Joules).
	oxidationChamber = "300"
	#Energy per operation tick (Joules).
	chemicalInfuser = "300"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "600"
	#Energy per operation tick (Joules).
	precisionSawmill = "75"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "600"
	#Energy per operation tick (Joules).
	chemicalWasher = "300"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "600"
	#Energy per operation tick (Joules).
	seismicVibrator = "75"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "10"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "150"
	#Energy per operation tick (Joules).
	laser = "15000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "150"
	#Energy per operation tick (Joules).
	modificationStation = "150"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "300"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "300"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "15000"
	#Energy per operation tick (Joules).
	pigmentExtractor = "300"
	#Energy per operation tick (Joules).
	pigmentMixer = "300"
	#Energy per operation tick (Joules).
	paintingMachine = "125"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "7500"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1500"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "20"
		#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
		teleporterDimensionPenalty = "15000"

